export const WIKI_TYPES = [
  { value: "mua-bat-dong-san", label: "mua bất động sản" },
  { value: "ban-bat-dong-san", label: "bán bất động sản" },
  { value: "thue-bat-dong-san", label: "thuê bất động sản" },
  { value: "tai-chinh", label: "tài chính" },
  { value: "quy-hoach-phap-ly", label: "quy hoạch, pháp lý" },
  { value: "noi-that-ngoai-that", label: "nội thất, ngoại thất" },
  { value: "phong-thuy", label: "phong thủy" },
];
export const PHONEBOOK_TYPES = [
  { value: "nha-moi-gioi", label: "nhà môi giới" },
  { value: "doanh-nghiep", label: "doanh nghiệp" },
];
export const PROPERTY_TYPES = [
  { value: "tat-ca", label: "tất cả loại nhà đất" },
  { value: "can-ho-chung-cu", label: "căn hộ chung cư" },
  {
    value: "chung-cu-mini-can-ho-dich-vu",
    label: "chung cư mini, căn hộ dịch vụ",
  },
  { value: "nha-rieng", label: "nhà riêng" },
  { value: "nha-biet-thu-lien-ke", label: "nhà biệt thự, liền kề" },
  { value: "nha-mat-pho", label: "nhà mặt phố" },
  {
    value: "shophouse-nha-pho-thuong-mai",
    label: "shophouse, nhà phố thương mại",
  },
  { value: "dat-nen-du-an", label: "đất nền dự án" },
  { value: "dat", label: "đất" },
  { value: "trang-trai-khu-nghi-duong", label: "trang trại, khu nghỉ dưỡng" },
  { value: "condotel", label: "condotel" },
  { value: "kho-nha-xuong", label: "kho, nhà xưởng" },
  { value: "cua-hang-kiot", label: "cửa hàng, kiot" },
  { value: "nha-tro-phong-tro", label: "nhà trọ, phòng trọ" },
  { value: "van-phong", label: "văn phòng" },
  { value: "loai-nha-dat-khac", label: "loại nhà đất khác" },
];
export const projectTypes = [
  { value: "tat-ca", label: "tất cả loại dự án" },
  { value: "can-ho-chung-cu", label: "căn hộ chung cư" },
  { value: "cao-oc-van-phong", label: "cao ốc văn phòng" },
  { value: "trung-tam-thuong-mai", label: "trung tâm thương mại" },
  { value: "khu-do-thi-moi", label: "khu đô thị mới" },
  { value: "khu-phuc-hop", label: "khu phức hợp" },
  { value: "nha-o-xa-hoi", label: "nhà ở xã hội" },
  { value: "khu-nghi-duong-sinh-thai", label: "khu nghỉ dưỡng, sinh thái" },
  { value: "khu-cong-nghiep", label: "khu công nghiệp" },
  { value: "biet-thu-lien-ke", label: "biệt thự liền kề" },
  { value: "shophouse", label: "shophouse" },
  { value: "nha-mat-pho", label: "nhà mặt phố" },
  { value: "loai du an khac", label: "loại dự án khác" },
];
export const PRICE_FILTERS = {
  buying: [
    { value: "tat-ca", label: "tất cả mức giá" },
    { value: "duoi-500-trieu", label: "dưới 500 triệu" },
    { value: "500-800-trieu", label: "500 - 800 triệu" },
    { value: "800-trieu-1-ty", label: "800 triệu - 1 tỷ" },
    { value: "1-2-ty", label: "1 - 2 tỷ" },
    { value: "2-3-ty", label: "2 - 3 tỷ" },
    { value: "3-4-ty", label: "3 - 4 tỷ" },
    { value: "4-5-ty", label: "4 - 5 tỷ" },
    { value: "5-7-ty", label: "5 - 7 tỷ" },
    { value: "7-10-ty", label: "7 - 10 tỷ" },
    { value: "10-20-ty", label: "10 - 20 tỷ" },
    { value: "20-30-ty", label: "20 - 30 tỷ" },
    { value: "30-50-ty", label: "30 - 50 tỷ" },
    { value: "tren-50-ty", label: "trên 50 tỷ" },
  ],
  renting: [
    { value: "tat-ca", label: "tất cả mức giá" },
    { value: "duoi-1-trieu", label: "dưới 1 triệu" },
    { value: "1-3-trieu", label: "1 - 3 triệu" },
    { value: "3-5-trieu", label: "3 - 5 triệu" },
    { value: "5-10-trieu", label: "5 - 10 triệu" },
    { value: "10-40-trieu", label: "10 - 40 triệu" },
    { value: "40-70-trieu", label: "40 - 70 triệu" },
    { value: "70-100-trieu", label: "70 - 100 triệu" },
    { value: "tren-100-trieu", label: "trên 100 triệu" },
  ],
  project: [
    { value: "tat-ca", label: "tất cả mức giá" },
    { value: "duoi-5-trieu", label: "dưới 5 triệu" },
    { value: "5-30-trieu", label: "5 - 30 triệu" },
    { value: "10-20-trieu", label: "10 - 20 triệu" },
    { value: "20-35-trieu", label: "20 - 35 triệu" },
    { value: "50-80-trieu", label: "50 - 80 triệu" },
    { value: "tren-80-trieu", label: "trên 80 triệu" },
  ],
};
export const AREA_FILTERS = {
  property: [
    { value: "tat-ca", label: "tất cả diện tích" },
    { value: "duoi-30", label: "dưới 30 m2" },
    { value: "30-50", label: "30 - 50 m2" },
    { value: "50-70", label: "50 - 70 m2" },
    { value: "70-100", label: "70 - 100 m2" },
    { value: "100-150", label: "100 - 150 m2" },
    { value: "150-200", label: "150 - 200 m2" },
    { value: "200-300", label: "200 - 300 m2" },
    { value: "300-500", label: "200 - 300 m2" },
    { value: "tren-500", label: "trên 300 m2" },
  ],
  project: [
    { value: "tat-ca", label: "tất cả diện tích" },
    { value: "duoi-1", label: "dưới 1 ha" },
    { value: "1-10", label: "1 - 10 ha" },
    { value: "10-30", label: "10 - 30 ha" },
    { value: "30-50", label: "30 - 50 ha" },
    { value: "50-75", label: "50 - 75 ha" },
    { value: "75-100", label: "75 - 100 ha" },
    { value: "tren-100", label: "trên 100 ha" },
  ],
};

export const PROVINCES = [
  { value: "ha-noi", label: "Hà Nội" },
  { value: "tp-ho-chi-minh", label: "TP. Hồ Chí Minh" },
  { value: "da-nang", label: "Đà Nẵng" },
  { value: "hai-phong", label: "Hải Phòng" },
  { value: "can-tho", label: "Cần Thơ" },
  { value: "an-giang", label: "An Giang" },
  { value: "ba-ria-vung-tau", label: "Bà Rịa - Vũng Tàu" },
  { value: "bac-giang", label: "Bắc Giang" },
  { value: "bac-kan", label: "Bắc Kạn" },
  { value: "bac-lieu", label: "Bạc Liêu" },
  { value: "bac-ninh", label: "Bắc Ninh" },
  { value: "ben-tre", label: "Bến Tre" },
  { value: "binh-dinh", label: "Bình Định" },
  { value: "binh-duong", label: "Bình Dương" },
  { value: "binh-phuoc", label: "Bình Phước" },
  { value: "binh-thuan", label: "Bình Thuận" },
  { value: "ca-mau", label: "Cà Mau" },
  { value: "cao-bang", label: "Cao Bằng" },
  { value: "dak-lak", label: "Đắk Lắk" },
  { value: "dak-nong", label: "Đắk Nông" },
  { value: "dien-bien", label: "Điện Biên" },
  { value: "dong-nai", label: "Đồng Nai" },
  { value: "dong-thap", label: "Đồng Tháp" },
  { value: "gia-lai", label: "Gia Lai" },
  { value: "ha-giang", label: "Hà Giang" },
  { value: "ha-nam", label: "Hà Nam" },
  { value: "ha-tinh", label: "Hà Tĩnh" },
  { value: "hai-duong", label: "Hải Dương" },
  { value: "hau-giang", label: "Hậu Giang" },
  { value: "hoa-binh", label: "Hòa Bình" },
  { value: "hung-yen", label: "Hưng Yên" },
  { value: "khanh-hoa", label: "Khánh Hòa" },
  { value: "kien-giang", label: "Kiên Giang" },
  { value: "kon-tum", label: "Kon Tum" },
  { value: "lai-chau", label: "Lai Châu" },
  { value: "lam-dong", label: "Lâm Đồng" },
  { value: "lang-son", label: "Lạng Sơn" },
  { value: "lao-cai", label: "Lào Cai" },
  { value: "long-an", label: "Long An" },
  { value: "nam-dinh", label: "Nam Định" },
  { value: "nghe-an", label: "Nghệ An" },
  { value: "ninh-binh", label: "Ninh Bình" },
  { value: "ninh-thuan", label: "Ninh Thuận" },
  { value: "phu-tho", label: "Phú Thọ" },
  { value: "phu-yen", label: "Phú Yên" },
  { value: "quang-binh", label: "Quảng Bình" },
  { value: "quang-nam", label: "Quảng Nam" },
  { value: "quang-ngai", label: "Quảng Ngãi" },
  { value: "quang-ninh", label: "Quảng Ninh" },
  { value: "quang-tri", label: "Quảng Trị" },
  { value: "soc-trang", label: "Sóc Trăng" },
  { value: "son-la", label: "Sơn La" },
  { value: "tay-ninh", label: "Tây Ninh" },
  { value: "thai-binh", label: "Thái Bình" },
  { value: "thai-nguyen", label: "Thái Nguyên" },
  { value: "thanh-hoa", label: "Thanh Hóa" },
  { value: "thua-thien-hue", label: "Thừa Thiên Huế" },
  { value: "tien-giang", label: "Tiền Giang" },
  { value: "tra-vinh", label: "Trà Vinh" },
  { value: "tuyen-quang", label: "Tuyên Quang" },
  { value: "vinh-long", label: "Vĩnh Long" },
  { value: "vinh-phuc", label: "Vĩnh Phúc" },
  { value: "yen-bai", label: "Yên Bái" },
];
export const POST_TYPES = [
  {
    value: "mua-ban",
    label: "Mua bán",
    filters: [
      { value: "thanhPho", label: "Thành phố", items: PROVINCES },
      { value: "loaiNhaDat", label: "Loại nhà đất", items: PROPERTY_TYPES },
      { value: "mucGia", label: "Mức giá", items: PRICE_FILTERS.buying },
      { value: "dienTich", label: "Diện tích", items: AREA_FILTERS.property },
    ],
  },
  {
    value: "cho-thue",
    label: "Cho thuê",
    filters: [
      { value: "thanhPho", label: "Thành phố", items: PROVINCES },
      { value: "loaiNhaDat", label: "Loại nhà đất", items: PROPERTY_TYPES },
      { value: "mucGia", label: "Mức giá", items: PRICE_FILTERS.renting },
      { value: "dienTich", label: "Diện tích", items: AREA_FILTERS.property },
    ],
  },
  {
    value: "du-an",
    label: "Dự án",
    filters: [
      { value: "thanhPho", label: "Thành phố", items: PROVINCES },
      { value: "loaiDuAn", label: "Loại dự án", items: projectTypes },
      { value: "mucGia", label: "Mức giá", items: PRICE_FILTERS.project },
      { value: "dienTich", label: "Diện tích", items: AREA_FILTERS.project },
    ],
  },
];

export const MOCK_PROPERTIES = [
  {
    id: "1",
    title: "Căn hộ cao cấp The Gold View 2 phòng ngủ, full nội thất",
    address: "Quận 4, TP. Hồ Chí Minh",
    price: 3200000000,
    area: 75,
    bedrooms: 2,
    bathrooms: 2,
    description:
      "Căn hộ cao cấp The Gold View, thiết kế hiện đại, đầy đủ nội thất cao cấp. Vị trí đắc địa, view đẹp, gần trung tâm thành phố.",
    type: "Căn hộ",
    transactionType: "Bán",
    postedDate: "10/04/2025",
    owner: {
      name: "Nguyễn Văn A",
      phone: "0901234567",
      email: "nguyenvana@example.com",
    },
    status: "approved",
    images: [
      "https://images.pexels.com/photos/1571460/pexels-photo-1571460.jpeg",
      "https://images.pexels.com/photos/1643383/pexels-photo-1643383.jpeg",
      "https://images.pexels.com/photos/1457842/pexels-photo-1457842.jpeg",
    ],
    features: ["Ban công", "Hồ bơi", "Gym", "An ninh 24/7", "Parking"],
  },
  {
    id: "2",
    title: "Nhà phố mặt tiền đường Nguyễn Trãi, vị trí kinh doanh đắc địa",
    address: "Quận 1, TP. Hồ Chí Minh",
    price: 15500000000,
    area: 120,
    bedrooms: 4,
    bathrooms: 5,
    description:
      "Nhà phố mặt tiền đường Nguyễn Trãi, vị trí đắc địa, thích hợp kinh doanh. Cấu trúc 1 trệt 3 lầu, thiết kế hiện đại.",
    type: "Nhà phố",
    transactionType: "Bán",
    postedDate: "05/04/2025",
    owner: {
      name: "Trần Thị B",
      phone: "0912345678",
      email: "tranthib@example.com",
    },
    status: "approved",
    images: [
      "https://images.pexels.com/photos/323780/pexels-photo-323780.jpeg",
      "https://images.pexels.com/photos/1029599/pexels-photo-1029599.jpeg",
      "https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg",
    ],
    features: ["Mặt tiền", "Thang máy", "Sân thượng", "Parking"],
  },
  {
    id: "3",
    title: "Cho thuê căn hộ Masteri Thảo Điền 2PN view sông",
    address: "Quận 2, TP. Hồ Chí Minh",
    price: 15000000,
    area: 68,
    bedrooms: 2,
    bathrooms: 2,
    description:
      "Cho thuê căn hộ Masteri Thảo Điền 2 phòng ngủ view sông, full nội thất cao cấp. Tiện ích đầy đủ, an ninh 24/7.",
    type: "Căn hộ",
    transactionType: "Cho thuê",
    postedDate: "12/04/2025",
    owner: {
      name: "Lê Văn C",
      phone: "0987654321",
      email: "levanc@example.com",
    },
    status: "approved",
    images: [
      "https://images.pexels.com/photos/1438832/pexels-photo-1438832.jpeg",
      "https://images.pexels.com/photos/1743227/pexels-photo-1743227.jpeg",
      "https://images.pexels.com/photos/275484/pexels-photo-275484.jpeg",
    ],
    features: ["View sông", "Hồ bơi", "Gym", "An ninh 24/7", "Parking"],
  },
  {
    id: "4",
    title: "Bán đất nền dự án khu đô thị mới Long Thành, sổ đỏ riêng",
    address: "Huyện Long Thành, Đồng Nai",
    price: 2800000000,
    area: 100,
    bedrooms: 0,
    bathrooms: 0,
    description:
      "Bán đất nền dự án khu đô thị mới Long Thành, vị trí đắc địa, gần sân bay quốc tế Long Thành, sổ đỏ riêng từng nền.",
    type: "Đất nền",
    transactionType: "Bán",
    postedDate: "08/04/2025",
    owner: {
      name: "Phạm Văn D",
      phone: "0923456789",
      email: "phamvand@example.com",
    },
    status: "approved",
    images: [
      "https://images.pexels.com/photos/7031406/pexels-photo-7031406.jpeg",
      "https://images.pexels.com/photos/6492397/pexels-photo-6492397.jpeg",
      "https://images.pexels.com/photos/3935333/pexels-photo-3935333.jpeg",
    ],
    features: ["Sổ đỏ", "Khu đô thị", "Hạ tầng hoàn thiện"],
  },
  {
    id: "5",
    title: "Biệt thự Vinhomes Riverside, đầy đủ nội thất cao cấp",
    address: "Quận Long Biên, Hà Nội",
    price: 28000000000,
    area: 300,
    bedrooms: 5,
    bathrooms: 6,
    description:
      "Biệt thự Vinhomes Riverside, thiết kế sang trọng, đầy đủ nội thất cao cấp. Khu vực an ninh, tiện ích đẳng cấp.",
    type: "Biệt thự",
    transactionType: "Bán",
    postedDate: "03/04/2025",
    owner: {
      name: "Hoàng Thị E",
      phone: "0934567890",
      email: "hoangthie@example.com",
    },
    status: "approved",
    images: [
      "https://images.pexels.com/photos/1396132/pexels-photo-1396132.jpeg",
      "https://images.pexels.com/photos/1643384/pexels-photo-1643384.jpeg",
      "https://images.pexels.com/photos/1732414/pexels-photo-1732414.jpeg",
    ],
    features: ["Sân vườn", "Hồ bơi", "Gym", "An ninh 24/7", "Parking"],
  },
  {
    id: "6",
    title: "Cho thuê văn phòng hạng A tòa nhà Lim Tower",
    address: "Quận 1, TP. Hồ Chí Minh",
    price: 35000000,
    area: 120,
    bedrooms: 0,
    bathrooms: 2,
    description:
      "Cho thuê văn phòng hạng A tòa nhà Lim Tower, vị trí trung tâm, view đẹp, đầy đủ tiện ích.",
    type: "Văn phòng",
    transactionType: "Cho thuê",
    postedDate: "14/04/2025",
    owner: {
      name: "Vũ Văn F",
      phone: "0945678901",
      email: "vuvanf@example.com",
    },
    status: "approved",
    images: [
      "https://images.pexels.com/photos/269077/pexels-photo-269077.jpeg",
      "https://images.pexels.com/photos/380768/pexels-photo-380768.jpeg",
      "https://images.pexels.com/photos/260931/pexels-photo-260931.jpeg",
    ],
    features: ["Thang máy", "Lễ tân", "An ninh 24/7", "Parking"],
  },
];
